<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>bullets.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="aim.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="4.1.0" />
    <PackageReference Include="SFML.Net" Version="2.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="aim.ico" />
  </ItemGroup>

</Project>
